### ISSUE TITLE
thunderbird-gnome-support is not installable

### ISSUE THREAD

**Issue by rhanneken** [pop-os/packaging-thunderbird#4]
I'm not sure I'm reporting this problem in the right place, but I'm unable to install the package `thunderbird-gnome-support`.  When I enter `sudo apt install thunderbird-gnome-support`, I get this error message:

```
The following packages have unmet dependencies:
 thunderbird-gnome-support : Depends: thunderbird (= 1:115.13.0+build5-0ubuntu0.22.04.1) but 2:128.0.1esr~1722554880~22.04~68ae58a is to be installed
E: Unable to correct problems, you have held broken packages.
```

I'm using Pop!_OS 22.04 LTS.

**Comment by jacobgkau** [comment]
You're in the right place. We recently packaged Thunderbird for 24.04 because Ubuntu moved it to a snap. It looks like it got released on 22.04 in https://github.com/pop-os/repo-release/pull/354.

We need to decide whether we're going to also package a fork of thunderbird-gnome-support, or pull our packaging from 22.04. If it's the latter, we need to rename this repo's `master` branch to `master_noble` so it stops getting built for noble.

@mmstick What do you think? Probably easier to rename the branch since we won't need the GNOME support package in 24.04, right? It looks like the GNOME support package doesn't even exist in Ubuntu anymore for 24.04, so we won't be taking anything away from 24.04 users who go out of their way to use GNOME.

**Comment by jacobgkau** [comment]
This could present a problem if downgrading from the released version causes an issue. We should test that before we pull our packaging from 22.04, now that it's been released.

**Comment by jacobgkau** [comment]
Looking at the [gnome-support package](https://packages.ubuntu.com/jammy-updates/thunderbird-gnome-support), it seems to be built from the main Thunderbird source package, but it just depends on a few other packages to pull in libraries. Maybe it wouldn't be too bad to package, if rolling back doesn't turn out to be an option.

@rhanneken Can you tell us what functionality you get from this package? Does installing `libmessaging-menu0` with `sudo apt install libmessaging-menu0` get you the functionality back? That seems to be the only dependency that's not required by other Pop!_OS components.

**Comment by rhanneken** [comment]
I'm not sure what I'm missing without thunderbird-gnome-support, but when I try to compose a message, it looks like this:

![image](https://github.com/user-attachments/assets/8025c1b3-9aac-45d4-bf60-a915e07438e6)

**Comment by rhanneken** [comment]
Also, strangely, it seems like I can't add Thunderbird to the dock.

**Comment by rhanneken** [comment]
> This could present a problem if downgrading from the released version causes an issue with Thunderbird's user data.

Yeah, I tried downgrading (`sudo apt install thunderbird=…`), but it refused to run because a newer version of Thunderbird had upgraded my user profile.

**Comment by squalou** [comment]
Hi, arrived here for a similar issue : with thunderbird 128 on pop 22.04, no icon is displayed in task bar.

I mean : default app icon shows up instead, and there's no way to pin it. Thought about installing gnome-support package ... so here I am :)

Weird thing is that when launched, the app is reported as 'thunderbird-esr' whereas the binary, the icon and the wm-class name  in .desktop file is referred to as 'thunderbird'.

On the other hand I did not see any other issue, maybe because I use a specific theme that could hide issues.

**Comment by woeisme** [comment]
chiming in here, arrived at this report because I cannot run PopShop system upgrades due to:

> The following packages have unmet dependencies:
  thunderbird-gnome-support: Depends: thunderbird (= 1:115.13.0+build5-0ubuntu0.22.04.1) but 2:128.0.1esr~1722554880~22.04~68ae58a is to be installed


![image](https://github.com/user-attachments/assets/d8b8713b-f6ff-4555-aa16-0b78c3d92ddc)

How should I proceed?

**Comment by woeisme** [comment]
I'd ask why this is closed as completed? 

I see the branch has been updated and merged but I'm still getting the same error, does it take some time to percolate out to the general updates repositories?

**Comment by leviport** [comment]
Updates will be released in the morning.

**Comment by jacobgkau** [comment]
`thunderbird-gnome-support` with a version matching the Thunderbird package is now available in the Pop!_OS release repo.

**Comment by rhanneken** [comment]
> `thunderbird-gnome-support` with a version matching the Thunderbird package is now available in the Pop!_OS release repo.

Thanks, I appreciate the effort. Alas, my problems have not been solved, which makes me think the issue isi with the thunderbird package. I can probably solve my look-and-feel issue myself, but there's still the problem of not being able to pin Thunderbird to the dock. Shall I create another GitHub issue?

**Comment by jacobgkau** [comment]
I see the issue, looking into the cause.

**Comment by jacobgkau** [comment]
I also see the theme issue in light mode only.

**Comment by rhanneken** [comment]
Here's what I believe:

1. The reason there's no option to pin Thunderbird to the dash is that GNOME can't find a `.desktop` file matching the running application.
2. There actually is a `/usr/share/applications/thunderbird.desktop`. 
3. Inside `thunderbird.desktop`, there's a field called `Exec`, and the value is "thunderbird %u."
4. If you run Thunderbird and open the hamburger menu, then select Help->Troubleshooting Information, you'll see a field labeled "Application Binary."
5. If you're running the last Ubuntu-packaged Thunderbird, the value of "Application Binary" is "/usr/lib/thunderbird/thunderbird."
6. If you're running the new Thunderbird package, the value of "Application Binary" is "/usr/lib/thunderbird/thunderbird-bin."
7. I think because "thunderbird-bin" isn't part of the value for `Exec` in `thunderbird.desktop`, GNOME is deciding that `thunderbird.desktop` is unrelated to the running Thunderbird process.
8. I think a similar discrepancy ("firefox" _vs_. "firefox-bin") is responsible for pop-os/pop#2314.

What I haven't been able to figure out is what the packaging of thunderbird has to do with what Thunderbird reports as its binary filepath.

**Comment by jacobgkau** [comment]
It doesn't use the `Exec` line, it uses the `StartupWMClass` line. I've already made a fix for it here: https://github.com/pop-os/packaging-thunderbird/pull/7 

The theme issue is a GTK theme issue, which we have to be careful with since that's also used for Firefox: https://github.com/pop-os/gtk-theme/issues/606 In the meantime, you can work around this one by setting any other theme (like the built-in Light theme) within the Thunderbird settings.

**Comment by rhanneken** [comment]
That's great news, and thanks for the fix. Sounds like my theory was a little off. Maybe you should investigate pop-os/pop#2314. I believe it's basically the same issue.

**Comment by jacobgkau** [comment]
The `xprop` command shows that the `WM_CLASS` string for Firefox is just plain `firefox`, which is what's in the `firefox.desktop` file, so it's not the same issue as the dock pinning problem. (We ship regular release Firefox and extended support release Thunderbird at this time; the different release channel is why the .desktop file has to specify a different class. Mozilla presumably has them send separate classes in case you want to use both at once.)

The default applications mechanism may use `Exec` or something else other than `StartupWMClass`. I'll take a look at that when possible, at least for 24.04.

**Comment by rhanneken** [comment]
For what it's worth, I believe Firefox is falling into [this code path](https://hg.mozilla.org/mozilla-central/file/tip/browser/components/shell/nsGNOMEShellService.cpp#l296) and creating a new `.desktop` file instead of using the existing one.
